apiVersion: v1
kind: ConfigMap
metadata:
  name: note-config
  namespace: aklp
  labels:
    app: aklp-note
data:
  APP_NAME: "aklp-note"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/aklp_note"