apiVersion: v1
kind: Service
metadata:
  name: aklp-note
  namespace: aklp
  labels:
    app: aklp-note
spec:
  type: NodePort
  selector:
    app: aklp-note
  ports:
    - port: 8002
      targetPort: http
      nodePort: 30002
      protocol: TCP
      name: http