apiVersion: v1
kind: Service
metadata:
  name: aklp-agent
  namespace: aklp
  labels:
    app: aklp-agent
spec:
  type: NodePort
  selector:
    app: aklp-agent
  ports:
    - port: 8001
      targetPort: http
      nodePort: 30001
      protocol: TCP
      name: http
