apiVersion: v1
kind: ConfigMap
metadata:
  name: task-config
  namespace: aklp
  labels:
    app: aklp-task
data:
  APP_NAME: "aklp-task"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/aklp_task"