apiVersion: v1
kind: Service
metadata:
  name: aklp-task
  namespace: aklp
  labels:
    app: aklp-task
spec:
  type: NodePort
  selector:
    app: aklp-task
  ports:
    - port: 8003
      targetPort: http
      nodePort: 30003
      protocol: TCP
      name: http